repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/ansible/ansible-lint.git
  #   rev: v24.2.1
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$
  #       name: Ansible Lint
  #       description: Run configurations on .ansible-lint file
  #       verbose: true
  #       # args: [-p, ./ansible/*]
