---
# Playbook for file server
# ---

- hosts: all
  become: True
  roles:
    - role: maxhoesel.smallstep.step_bootstrap_host
      vars:
        step_bootstrap_ca_url: https://pki.barrau.bzh
        step_bootstrap_fingerprint: b653f61258ffe0b3c646eb338272883ff5b8374ca09a8a49f55c4df6f02adfba
        step_bootstrap_users:
          - user: root
          - user: fredericbarrau

- hosts: wings
  become: True
  tasks:
    # This will download a certificate to /etc/step/ that you can then use in other applications.
    # See the step_acme_cert README for more options
    - name: Configure an ACME cert + renewal for fqdn cert
      ansible.builtin.include_role:
        name: maxhoesel.smallstep.step_acme_cert
      vars:
        step_acme_cert_ca_provisioner: ACME
        step_acme_cert_name: "{{ ansible_facts['fqdn'] }}"
        step_acme_cert_duration: 24h
        step_acme_cert_certfile: 
          path: /etc/ssl/certs/{{ ansible_facts['fqdn'] }}.crt
        step_acme_cert_keyfile:
          path: /etc/ssl/private/{{ ansible_facts['fqdn'] }}.pem
        step_acme_cert_renewal_service: "step-renew-{{ ansible_facts['fqdn'] }}"
        step_acme_cert_renewal_reload_services:
          - wings

- hosts: file_server
  become: True
  tasks:
      # This will download a certificate to /etc/step/ that you can then use in other applications.
      # See the step_acme_cert README for more options
      - name: Configure an ACME cert + renewal
        ansible.builtin.include_role:
          name: maxhoesel.smallstep.step_acme_cert
        vars:
          step_acme_cert_ca_provisioner: ACME
          step_acme_cert_name: pterodactyl.barrau.bzh
          #step_acme_cert_duration: 24h
          step_acme_cert_duration: 1h
          step_acme_cert_certfile: 
            path: /etc/ssl/certs/pterodactyl.barrau.bzh.crt
          step_acme_cert_keyfile:
            path: /etc/ssl/private/pterodactyl.barrau.bzh.pem
          step_acme_cert_renewal_reload_services:
            - apache2
          step_acme_cert_renewal_service: "step-renew-pterodactyl.barrau.bzh"
      - name: Install Pterodactyl Panel
        include_role:
          name: maxhoesel.pterodactyl.pterodactyl_panel
        # pterodactyl_panel supports additional options, see it's README for more details.
        vars:
          pterodactyl_panel_app_key: base64:7qTrSglChckmSi3o+IZ8vJTQShsdiE3cJ0Vc4wicsiI=
          pterodactyl_panel_hashids_salt: hnpbfmz4puG5zXFIgKHO
          # The timezone in which the panel should operate
          pterodactyl_panel_timezone: Europe/Paris
          # DB settings. Make sure that the database + user already exist and are accessible
          pterodactyl_panel_db_host: "127.0.0.1"
          pterodactyl_panel_db_name: panel
          pterodactyl_panel_db_user: pterodactyl
          pterodactyl_panel_db_password: pterodactyl
          # Paths to the certificate. This defaults to the Let's Encrypt directory for your hosts domain name
          pterodactyl_panel_ssl_cert: "/etc/ssl/certs/pterodactyl.barrau.bzh.crt"
          pterodactyl_panel_ssl_key: "/etc/ssl/private/pterodactyl.barrau.bzh.pem"
          pterodactyl_panel_ssl_mode: none
          # Mail server settings.
          # pterodactyl_panel_mail_host: smtp.gmail.com
          # pterodactyl_panel_mail_user: your-address@gmail.com
          # pterodactyl_panel_mail_password: your-mail-password
          # pterodactyl_panel_mail_encryption: tls
          # By default, the role will create a user with the credentials admin/admin.
          # You can change these values below or in the UI once the panel is up and running
          pterodactyl_panel_admin_mail: "frederic.barrau@gmail.com"
          #pterodactyl_panel_admin_user: admin
          #pterodactyl_panel_admin_password: admin
  roles:
    - avahi
    - common
    - docker
    - nfs_file_server
    - samba_file_server
    - monitoring
    - wake-on-lan
    - geerlingguy.mysql
    - role: maxhoesel.pterodactyl.pterodactyl_wings
      vars:
        pterodactyl_wings_config:
          # Wing Ids
          uuid: b832f488-b83b-48fd-b9e1-2db17bf8d295
          token_id: wvzJ7NJoCT1hKft1
          token: 3ZKNuvhYyJhpyXgM7tdkf5m7QE8fO8DXxCQqrHIcWdvilde7KCoxa5JCwLZB2ec1
          remote: https://pterodactyl.barrau.bzh
          api:
            host: 0.0.0.0
            port: 8080
            ssl:
              enabled: true
              cert: "/etc/ssl/certs/{{ ansible_facts['fqdn'] }}.crt"
              key: "/etc/ssl/private/{{ ansible_facts['fqdn'] }}.pem"
            upload_limit: 100
          system:
            data: /var/lib/pterodactyl/volumes
            sftp:
              bind_port: 2022
          allowed_mounts: []

# Playbook for dns/pihole server:
# ---
- hosts: dns_pihole_server
  become: True
  roles:
    - avahi
    - common
    - docker
    - pihole

# Playbook for media_center server:
# ---
- hosts: media_center_server
  become: True
  roles:
    - avahi
    - common
    - docker
    - samba_file_server
    - minecraft
    - root_ca_keycert # Setup the root ca key & cert
    - role: maxhoesel.smallstep.step_ca
      vars:
        step_ca_name: Barrau's Private CA
        step_ca_dns: "pki.barrau.bzh,{{ ansible_default_ipv4.address | d('') }},{{ ansible_default_ipv6.address | d('') }}"
        step_ca_url: "https://pki.barrau.bzh:443"
        step_ca_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66653666636534313464633937326666646630396135653765613466633066616164333636353162
          3965323632303232363630373666656163656139623964660a346162326530373639383366633462
          39643064393032353036323132323636346434383637643863643161376437356338383531353165
          3961383930663231320a636136353863326663626561366364376539393465303032653339653430
          38613465373766383064356534346363386166363230333332336238393936363431
        step_ca_intermediate_name: Barrau's Intermediate CA
        step_ca_intermediate_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32636363616136326131313665386532663631316338333963613631303534656439313534336639
          6536306331363834376639353633656663333930613865320a316634303762666232323434363035
          32393034366131346239626130386530653366353365373437616265326333633761616337393966
          3531373262636430340a623734376466326461346263306365383965333735376263316663396631
          34626362353061623437646532316333656235363166353866636333346337383639
        step_ca_existing_root: remote
        step_ca_existing_root_file: /etc/ca/certs/root.cert.pem
        step_ca_existing_key: remote
        step_ca_existing_key_file: /etc/ca/private/root.key.pem
        step_ca_existing_key_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66653666636534313464633937326666646630396135653765613466633066616164333636353162
          3965323632303232363630373666656163656139623964660a346162326530373639383366633462
          39643064393032353036323132323636346434383637643863643161376437356338383531353165
          3961383930663231320a636136353863326663626561366364376539393465303032653339653430
          38613465373766383064356534346363386166363230333332336238393936363431
    - role: maxhoesel.pterodactyl.pterodactyl_wings
      vars:
        pterodactyl_wings_config:
          # Wing Ids
          uuid: a084b1b9-c4b9-48a6-8d29-ea1e6dc3365e
          token_id: my8lRfQT1XyYHApn
          token: u5fJqswld6AJpsSYKO4xFur3Iy63MkhJCOiBy6Dn6gC2eAR3hh64yvBEPPqp3xE7
          remote: https://pterodactyl.barrau.bzh
          api:
            host: 0.0.0.0
            port: 8080
            ssl:
              enabled: true
              cert: "/etc/ssl/certs/{{ ansible_facts['fqdn'] }}.crt"
              key: "/etc/ssl/private/{{ ansible_facts['fqdn'] }}.pem"
            upload_limit: 100
          system:
            data: /var/lib/pterodactyl/volumes
            sftp:
              bind_port: 2022
          allowed_mounts: []
    - wake-on-lan
  tasks:
    - name: Include Samba Server role
      ansible.builtin.include_role:
        name: vladgh.samba.server
    - name: Add an ACME provisioner to the CA
      maxhoesel.smallstep.step_ca_provisioner:
        name: ACME
        type: ACME
      become_user: step-ca
      notify: reload step-ca
  handlers:
    - name: reload step-ca
      systemd:
        name: step-ca
        state: reloaded

