# Playbook for file server
# ---

- hosts: file_server
  become: True
  roles:
    - common
    - file_server
    - monitoring
    - wake-on-lan

# Playbook for dns/pihole server:
# # ---
# - hosts: dns_pihole_server
#   become: True
#   roles:
#     - common
#     - pihole
