# Playbook for file server
# ---

- hosts: file_server
  become: True
  roles:
    - avahi
    - common
    - docker
    - nfs_file_server
    - samba_file_server
    - monitoring
    - wake-on-lan

# Playbook for dns/pihole server:
# ---
- hosts: dns_pihole_server
  become: True
  roles:
    - avahi
    - airplay
    - common
    - docker
    - pihole

# Playbook for media_center server:
# ---
- hosts: media_center_server
  become: True
  roles:
    - avahi
    - common
    - samba_file_server
    - minecraft
    - wake-on-lan
  tasks:
    - name: Include Samba Server role
      ansible.builtin.include_role:
        name: vladgh.samba.server