# Playbook for file server
# ---

- hosts: file_server
  become: True
  roles:
    - avahi
    - common
    - docker
    - file_server
    - monitoring
    - wake-on-lan

# Playbook for dns/pihole server:
# ---
- hosts: dns_pihole_server
  become: True
  roles:
    - avahi
    - airplay
    - common
    - docker
    - pihole

# Playbook for media_center server:
# ---
- hosts: media_center_server
  become: True
  roles:
    - avahi
    - common
    - wake-on-lan