- name: Install Docker on Debian
  block:
  - name: Add Docker Apt key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/raspbian/gpg
      dest: /etc/apt/keyrings/docker.asc
  
  - name: Add Docker Apt repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=armhf signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/raspbian {{ ansible_distribution_release | lower }} stable"
      state: present
      filename: docker
