# The handler is a task that will be executed only if a task notifies it.
# The handler is a separate file in the handlers directory.

# handler for avahi daemon restart
- name: restart avahi-daemon
  service:
    name: avahi-daemon
    state: restarted

# Restart the hostname service
- name: restart hostname
  service:
    name: systemd-hostnamed
    state: restarted

# Restart wakeonlan
- name: restart wakeonlan
  service:
    name: wakeonlan
    state: restarted
