- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/pterodactyl.barrau.bzh.pem

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: /etc/ssl/private/pterodactyl.barrau.bzh.csr
    privatekey_path: /etc/ssl/private/pterodactyl.barrau.bzh.pem
    common_name: pterodactyl.barrau.bzh

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/certs/pterodactyl.barrau.bzh.crt
    privatekey_path: /etc/ssl/private/pterodactyl.barrau.bzh.pem
    csr_path: /etc/ssl/private/pterodactyl.barrau.bzh.csr
    provider: selfsigned