# The handler is a task that will be executed only if a task notifies it.
# The handler is a separate file in the handlers directory.

# Restart wakeonlan
- name: restart wakeonlan
  service:
    name: wakeonlan-{{item}}
    state: restarted
  with_items: "{{ ansible_interfaces |map('regex_search', '^(enp|ens|eth).*$')|select('string') }}"

