---
# The common rules for all servers on our infrastructure:
# Setup:
# - Update the system automatically
# - Install the necessary packages
# - Configure the timezone
# - Configure the hostname
# - Configure the unattended-upgrades

- name: Install the necessary packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - avahi-daemon # bonjour for ubuntu
    - ca-certificates
    - curl
    - software-properties-common
    - logrotate
    - unattended-upgrades

- name: Configure the timezone
  timezone:
    name: "{{ timezone }}"

- name: Configure the hostname
  hostname:
    name: "{{ hostname }}"
  notify: restart hostname

- name: Configure the unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

# Configure avahi-daemon
- name: Configure avahi-daemon
  template:
    src: avahi-daemon.conf.j2
    dest: /etc/avahi/avahi-daemon.conf
    owner: root
    group: root
    mode: 0644
  notify: restart avahi-daemon
