# Remove the systemd-resolved package:
- name: Remove the systemd-resolved package
  package:
    name: systemd-resolved
    state: absent
  register: remove_systemd_resolved
  tags:
    - pihole

# No systemd-resolved package is installed: we need to configure the DNS resolver
- name: Configure the DNS resolver
  copy:
    content: |
      # Managed by Ansible
      # filename: /etc/resolv.conf
      nameserver 10.0.0.1
      search .local
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0444
  tags:
    - pihole

- name: create the pihole group
  group:
    name: pihole
  tags:
    - pihole

- name: create the pihole user
  user:
    name: pihole
    state: present
    shell: /bin/bash
    createhome: yes
    group: pihole
    groups: docker
  tags:
    - pihole

# Create subfolders for storing persistent configuration files of dnsmasq and pihole
- name: Create the pihole directories for docker compose file
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: pihole
    group: pihole
    mode: 0775
  loop:
    - /etc/pihole
    - /etc/dnsmasq.d
    - /var/lib/pihole-docker
    - /var/log/pihole
  register: pihole_directories
  tags:
    - pihole

- name: Copy the docker-compose file for pihole
  template:
    src: docker-compose.yml.j2
    dest: /var/lib/pihole-docker/docker-compose.yml
    owner: pihole
    group: docker
    mode: 0440
  tags:
    - pihole

- name: Install a local DNS cache
  apt:
    name: 
      - nscd
  tags:
    - pihole

# Add a systemd service wrapping the docker compose command to start pihole at boot time
- name: Copy the pihole systemd service configuration file
  copy:
    src: pihole.service
    dest: /etc/systemd/system/pihole.service
    owner: root
    group: root
    mode: 0644
  notify:
    
  tags:
    - pihole

# Ensure the pihole self signed CA is empty
- name: Remove self signed pihole CA
  ansible.builtin.file:
    path: /etc/pihole/tls_ca.crt
    state: absent
  notify:
    - restart pihole service
  tags: 
    - pihole

# Start and enable the pihole service
- name: Start and enable the pihole service
  systemd:
    name: pihole
    state: started
    enabled: yes
  tags:
    - pihole


